//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\constantin.moscalu\\\\DataGripProjects\\\\Amdaris Data Lake")]
        public string ProjectLocation {
            get {
                return ((string)(this["ProjectLocation"]));
            }
            set {
                this["ProjectLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Database Release\\\\01 Sprint Releases")]
        public string ReleasesFolderPath {
            get {
                return ((string)(this["ReleasesFolderPath"]));
            }
            set {
                this["ReleasesFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$(System.DefaultWorkingDirectory)/_Amdaris Data Lake/Database Release/01 Sprint R" +
            "eleases")]
        public string RepositoryReleasesFolderPath {
            get {
                return ((string)(this["RepositoryReleasesFolderPath"]));
            }
            set {
                this["RepositoryReleasesFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUserStoryId {
            get {
                return ((string)(this["LastUserStoryId"]));
            }
            set {
                this["LastUserStoryId"] = value;
            }
        }
    }
}
